# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c248d766ec6f0cceeb19a5ee0ce50c617082d2dca5db7da46fc8b935122a755d4f9f69586c61f6762cf5241b47867996c87d1f3794cec1222ef1a2d6392ba5c9

test:
  secret_key_base: 2ea320ca09f12670c619aaddb21c54956835b07067a7086da37043e557db4fe7c16ae0a76869794fcf0f0c58b1983543fb59fc1ff5346ead1000a32e284bc64c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
